import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Navbar } from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import "@fortawesome/fontawesome-free/css/all.css";
import { Toaster } from "@/components/ui/sonner";

const Encode_SanFont = Encode_Sans({
  subsets: ["latin"],
  weight: ["100", "400", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Encode_SanFont.className}`}>
        <Navbar />
        <main className="p-5">{children}</main>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
